package ni.org.ics.a2cares.app.database.helpers;

import android.content.ContentValues;
import android.database.Cursor;

import java.util.Date;

import ni.org.ics.a2cares.app.database.constants.EncuestasDBConstants;
import ni.org.ics.a2cares.app.database.constants.MainDBConstants;
import ni.org.ics.a2cares.app.domain.survey.EncuestaCasa;

/**
 * Created by Miguel Salinas on 5/10/2017.
 * V1.0
 */
public class EncuestaCasaHelper {

    public static ContentValues crearEncuestaCasaContentValues(EncuestaCasa encuesta){
        ContentValues cv = new ContentValues();

        cv.put(EncuestasDBConstants.codigo, encuesta.getCodigo());
        cv.put(EncuestasDBConstants.casa, encuesta.getCasa().getCodigo());
        cv.put(EncuestasDBConstants.participante, encuesta.getParticipante());
        cv.put(EncuestasDBConstants.cuantasPersonas, encuesta.getCuantasPersonas());
        cv.put(EncuestasDBConstants.cuantasMujeres, encuesta.getCuantasMujeres());
        cv.put(EncuestasDBConstants.edadMujer1, encuesta.getEdadMujer1());
        cv.put(EncuestasDBConstants.edadMujer2, encuesta.getEdadMujer2());
        cv.put(EncuestasDBConstants.edadMujer3, encuesta.getEdadMujer3());
        cv.put(EncuestasDBConstants.edadMujer4, encuesta.getEdadMujer4());
        cv.put(EncuestasDBConstants.edadMujer5, encuesta.getEdadMujer5());
        cv.put(EncuestasDBConstants.edadMujer6, encuesta.getEdadMujer6());
        cv.put(EncuestasDBConstants.edadMujer7, encuesta.getEdadMujer7());
        cv.put(EncuestasDBConstants.edadMujer8, encuesta.getEdadMujer8());
        cv.put(EncuestasDBConstants.edadMujer9, encuesta.getEdadMujer9());
        cv.put(EncuestasDBConstants.edadMujer10, encuesta.getEdadMujer10());
        cv.put(EncuestasDBConstants.cuantosHombres, encuesta.getCuantosHombres());
        cv.put(EncuestasDBConstants.edadHombre1, encuesta.getEdadHombre1());
        cv.put(EncuestasDBConstants.edadHombre2, encuesta.getEdadHombre2());
        cv.put(EncuestasDBConstants.edadHombre3, encuesta.getEdadHombre3());
        cv.put(EncuestasDBConstants.edadHombre4, encuesta.getEdadHombre4());
        cv.put(EncuestasDBConstants.edadHombre5, encuesta.getEdadHombre5());
        cv.put(EncuestasDBConstants.edadHombre6, encuesta.getEdadHombre6());
        cv.put(EncuestasDBConstants.edadHombre7, encuesta.getEdadHombre7());
        cv.put(EncuestasDBConstants.edadHombre8, encuesta.getEdadHombre8());
        cv.put(EncuestasDBConstants.edadHombre9, encuesta.getEdadHombre9());
        cv.put(EncuestasDBConstants.edadHombre10, encuesta.getEdadHombre10());
        cv.put(EncuestasDBConstants.cantidadCuartos, encuesta.getCantidadCuartos());
        cv.put(EncuestasDBConstants.cantidadCuartosDormir, encuesta.getCantidadCuartosDormir());
        cv.put(EncuestasDBConstants.problemaAgua, encuesta.getProblemaAgua());
        cv.put(EncuestasDBConstants.hrsSinServicioAgua, encuesta.getHrsSinServicioAgua());
        cv.put(EncuestasDBConstants.frecuenciaSeVaAgua, encuesta.getFrecuenciaSeVaAgua());
        cv.put(EncuestasDBConstants.otraFrecuenciaSeVaAgua, encuesta.getOtraFrecuenciaSeVaAgua());
        cv.put(EncuestasDBConstants.tienePozo, encuesta.getTienePozo());
        cv.put(EncuestasDBConstants.tieneMedidorAgua, encuesta.getTieneMedidorAgua());
        cv.put(EncuestasDBConstants.tieneTanque, encuesta.getTieneTanque());
        cv.put(EncuestasDBConstants.ubicacionLlaveAgua, encuesta.getUbicacionLlaveAgua());
        cv.put(EncuestasDBConstants.llaveCompartida, encuesta.getLlaveCompartida());
        cv.put(EncuestasDBConstants.almacenaAgua, encuesta.getAlmacenaAgua());
        cv.put(EncuestasDBConstants.almacenaEnBarriles, encuesta.getAlmacenaEnBarriles());
        cv.put(EncuestasDBConstants.almacenaEnTanques, encuesta.getAlmacenaEnTanques());
        cv.put(EncuestasDBConstants.almacenaEnPilas, encuesta.getAlmacenaEnPilas());
        cv.put(EncuestasDBConstants.almacenaOtrosRecipientes, encuesta.getAlmacenaOtrosRecipientes());
        cv.put(EncuestasDBConstants.otrosRecipientes, encuesta.getOtrosRecipientes());
        cv.put(EncuestasDBConstants.numBarriles, encuesta.getNumBarriles());
        cv.put(EncuestasDBConstants.numTanques, encuesta.getNumTanques());
        cv.put(EncuestasDBConstants.numPilas, encuesta.getNumPilas());
        cv.put(EncuestasDBConstants.numOtrosRecipientes, encuesta.getNumOtrosRecipientes());
        cv.put(EncuestasDBConstants.barrilesTapados, encuesta.getBarrilesTapados());
        cv.put(EncuestasDBConstants.tanquesTapados, encuesta.getTanquesTapados());
        cv.put(EncuestasDBConstants.pilasTapadas, encuesta.getPilasTapadas());
        cv.put(EncuestasDBConstants.otrosRecipientesTapados, encuesta.getOtrosRecipientesTapados());
        cv.put(EncuestasDBConstants.cepillaPilas, encuesta.getCepillaPilas());
        cv.put(EncuestasDBConstants.frecCepillaPilas, encuesta.getFrecCepillaPilas());
        cv.put(EncuestasDBConstants.cambiadoCasa, encuesta.getCambiadoCasa());
        cv.put(EncuestasDBConstants.remodeladoCasa, encuesta.getRemodeladoCasa());
        cv.put(EncuestasDBConstants.ubicacionLavandero, encuesta.getUbicacionLavandero());
        cv.put(EncuestasDBConstants.materialParedes, encuesta.getMaterialParedes());
        cv.put(EncuestasDBConstants.materialPiso, encuesta.getMaterialPiso());
        cv.put(EncuestasDBConstants.materialTecho, encuesta.getMaterialTecho());
        cv.put(EncuestasDBConstants.otroMaterialParedes, encuesta.getOtroMaterialParedes());
        cv.put(EncuestasDBConstants.otroMaterialPiso, encuesta.getOtroMaterialPiso());
        cv.put(EncuestasDBConstants.otroMaterialTecho, encuesta.getOtroMaterialTecho());
        cv.put(EncuestasDBConstants.casaPropia, encuesta.getCasaPropia());
        cv.put(EncuestasDBConstants.tieneAbanico, encuesta.getTieneAbanico());
        cv.put(EncuestasDBConstants.tieneTelevisor, encuesta.getTieneTelevisor());
        cv.put(EncuestasDBConstants.tieneRefrigerador, encuesta.getTieneRefrigerador());
        cv.put(EncuestasDBConstants.tienAireAcondicionado, encuesta.getTienAireAcondicionado());
        cv.put(EncuestasDBConstants.numAbanicos, encuesta.getNumAbanicos());
        cv.put(EncuestasDBConstants.numTelevisores, encuesta.getNumTelevisores());
        cv.put(EncuestasDBConstants.numRefrigeradores, encuesta.getNumRefrigeradores());
        cv.put(EncuestasDBConstants.numAireAcondicionado, encuesta.getNumAireAcondicionado());
        cv.put(EncuestasDBConstants.aireAcondicionadoFuncionando, encuesta.getAireAcondicionadoFuncionando());
        cv.put(EncuestasDBConstants.lavadoraFuncionando, encuesta.getLavadoraFuncionando());
        cv.put(EncuestasDBConstants.tieneMuro, encuesta.getTieneMuro());
        cv.put(EncuestasDBConstants.tieneInternet, encuesta.getTieneInternet());
        cv.put(EncuestasDBConstants.tieneInodoro, encuesta.getTieneInodoro());
        cv.put(EncuestasDBConstants.cantInodoro, encuesta.getCantInodoro());
        cv.put(EncuestasDBConstants.cantLetrina, encuesta.getCantLetrina());
        cv.put(EncuestasDBConstants.tieneServicioEnergia, encuesta.getTieneServicioEnergia());
        cv.put(EncuestasDBConstants.tieneMedidorEnergia, encuesta.getTieneMedidorEnergia());
        cv.put(EncuestasDBConstants.casaDosPisos, encuesta.getCasaDosPisos());
        cv.put(EncuestasDBConstants.tieneOtrosServicios, encuesta.getTieneOtrosServicios());
        cv.put(EncuestasDBConstants.tieneVehiculo, encuesta.getTieneVehiculo());
        cv.put(EncuestasDBConstants.tieneMoto, encuesta.getTieneMoto());
        cv.put(EncuestasDBConstants.tieneCarro, encuesta.getTieneCarro());
        cv.put(EncuestasDBConstants.tieneMicrobus, encuesta.getTieneMicrobus());
        cv.put(EncuestasDBConstants.tieneCamioneta, encuesta.getTieneCamioneta());
        cv.put(EncuestasDBConstants.tieneCamion, encuesta.getTieneCamion());
        cv.put(EncuestasDBConstants.tieneOtroMedioTransAuto, encuesta.getTieneOtroMedioTransAuto());
        cv.put(EncuestasDBConstants.otroMedioTransAuto, encuesta.getOtroMedioTransAuto());
        cv.put(EncuestasDBConstants.anioFabMoto, encuesta.getAnioFabMoto());
        cv.put(EncuestasDBConstants.anioFabCarro, encuesta.getAnioFabCarro());
        cv.put(EncuestasDBConstants.anioFabMicrobus, encuesta.getAnioFabMicrobus());
        cv.put(EncuestasDBConstants.anioFabCamioneta, encuesta.getAnioFabCamioneta());
        cv.put(EncuestasDBConstants.anioFabCamion, encuesta.getAnioFabCamion());
        cv.put(EncuestasDBConstants.anioFabOtroMedioTrans, encuesta.getAnioFabOtroMedioTrans());
        cv.put(EncuestasDBConstants.marcaMoto, encuesta.getMarcaMoto());
        cv.put(EncuestasDBConstants.marcaCarro, encuesta.getMarcaCarro());
        cv.put(EncuestasDBConstants.marcaMicrobus, encuesta.getMarcaMicrobus());
        cv.put(EncuestasDBConstants.marcaCamioneta, encuesta.getMarcaCamioneta());
        cv.put(EncuestasDBConstants.marcaCamion, encuesta.getMarcaCamion());
        cv.put(EncuestasDBConstants.marcaOtroMedioTrans, encuesta.getMarcaOtroMedioTrans());
        cv.put(EncuestasDBConstants.tipoCocina, encuesta.getTipoCocina());
        cv.put(EncuestasDBConstants.cuantosQuemadores, encuesta.getCuantosQuemadores());
        cv.put(EncuestasDBConstants.tieneHorno, encuesta.getTieneHorno());
        cv.put(EncuestasDBConstants.cocinaConLenia, encuesta.getCocinaConLenia());
        cv.put(EncuestasDBConstants.ubicacionCocinaLenia, encuesta.getUbicacionCocinaLenia());
        cv.put(EncuestasDBConstants.periodicidadCocinaLenia, encuesta.getPeriodicidadCocinaLenia());
        cv.put(EncuestasDBConstants.numDiarioCocinaLenia, encuesta.getNumDiarioCocinaLenia());
        cv.put(EncuestasDBConstants.numSemanalCocinaLenia, encuesta.getNumSemanalCocinaLenia());
        cv.put(EncuestasDBConstants.numQuincenalCocinaLenia, encuesta.getNumQuincenalCocinaLenia());
        cv.put(EncuestasDBConstants.numMensualCocinaLenia, encuesta.getNumMensualCocinaLenia());
        cv.put(EncuestasDBConstants.tieneAnimales, encuesta.getTieneAnimales());
        cv.put(EncuestasDBConstants.tieneGallinas, encuesta.getTieneGallinas());
        cv.put(EncuestasDBConstants.tienePatos, encuesta.getTienePatos());
        cv.put(EncuestasDBConstants.tienePerros, encuesta.getTienePerros());
        cv.put(EncuestasDBConstants.tieneGatos, encuesta.getTieneGatos());
        cv.put(EncuestasDBConstants.tieneCerdos, encuesta.getTieneCerdos());
        cv.put(EncuestasDBConstants.tieneVacas, encuesta.getTieneVacas());
        cv.put(EncuestasDBConstants.tieneCabras, encuesta.getTieneCabras());
        cv.put(EncuestasDBConstants.tieneCaballos, encuesta.getTieneCaballos());
        cv.put(EncuestasDBConstants.tienePelibueys, encuesta.getTienePelibueys());
        cv.put(EncuestasDBConstants.tieneAves, encuesta.getTieneAves());
        cv.put(EncuestasDBConstants.tieneOtrosAnimales, encuesta.getTieneOtrosAnimales());
        cv.put(EncuestasDBConstants.cantidadGallinas, encuesta.getCantidadGallinas());
        cv.put(EncuestasDBConstants.cantidadPatos, encuesta.getCantidadPatos());
        cv.put(EncuestasDBConstants.cantidadPerros, encuesta.getCantidadPerros());
        cv.put(EncuestasDBConstants.cantidadGatos, encuesta.getCantidadGatos());
        cv.put(EncuestasDBConstants.cantidadCerdos, encuesta.getCantidadCerdos());
        cv.put(EncuestasDBConstants.cantidadVacas, encuesta.getCantidadVacas());
        cv.put(EncuestasDBConstants.cantidadCabras, encuesta.getCantidadCabras());
        cv.put(EncuestasDBConstants.cantidadCaballos, encuesta.getCantidadCaballos());
        cv.put(EncuestasDBConstants.cantidadPelibueys, encuesta.getCantidadPelibueys());
        cv.put(EncuestasDBConstants.cantidadAves, encuesta.getCantidadAves());
        cv.put(EncuestasDBConstants.cantidadOtrosAnimales, encuesta.getCantidadOtrosAnimales());
        cv.put(EncuestasDBConstants.gallinasDentroCasa, encuesta.getGallinasDentroCasa());
        cv.put(EncuestasDBConstants.patosDentroCasa, encuesta.getPatosDentroCasa());
        cv.put(EncuestasDBConstants.perrosDentroCasa, encuesta.getPerrosDentroCasa());
        cv.put(EncuestasDBConstants.gatosDentroCasa, encuesta.getGatosDentroCasa());
        cv.put(EncuestasDBConstants.cerdosDentroCasa, encuesta.getCerdosDentroCasa());
        cv.put(EncuestasDBConstants.vacasDentroCasa, encuesta.getVacasDentroCasa());
        cv.put(EncuestasDBConstants.cabrasDentroCasa, encuesta.getCabrasDentroCasa());
        cv.put(EncuestasDBConstants.caballosDentroCasa, encuesta.getCaballosDentroCasa());
        cv.put(EncuestasDBConstants.pelibueysDentroCasa, encuesta.getPelibueysDentroCasa());
        cv.put(EncuestasDBConstants.avesDentroCasa, encuesta.getAvesDentroCasa());
        cv.put(EncuestasDBConstants.otrosAnimalesDentroCasa, encuesta.getOtrosAnimalesDentroCasa());
        cv.put(EncuestasDBConstants.personaFumaDentroCasa, encuesta.getPersonaFumaDentroCasa());
        cv.put(EncuestasDBConstants.tieneRecoleccionBasura, encuesta.getTieneRecoleccionBasura());
        cv.put(EncuestasDBConstants.cuantasVecesRecBasura, encuesta.getCuantasVecesRecBasura());
        cv.put(EncuestasDBConstants.dondePasaRecBasura, encuesta.getDondePasaRecBasura());
        cv.put(EncuestasDBConstants.dondePasaRecBasuraOtros, encuesta.getDondePasaRecBasuraOtros());
        cv.put(EncuestasDBConstants.vistoAnimalesSalvajes, encuesta.getVistoAnimalesSalvajes());
        cv.put(EncuestasDBConstants.vistoAnimalesSalvajesOtros, encuesta.getVistoAnimalesSalvajesOtros());

        if (encuesta.getRecordDate() != null) cv.put(MainDBConstants.recordDate, encuesta.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, encuesta.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(encuesta.getPasive()));
        cv.put(MainDBConstants.estado, String.valueOf(encuesta.getEstado()));
        cv.put(MainDBConstants.deviceId, encuesta.getDeviceid());

        return cv;
    }

    public static EncuestaCasa crearEncuestaCasa(Cursor cursor){
        EncuestaCasa mEncuesta = new EncuestaCasa();

        mEncuesta.setCodigo(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.codigo)));
        mEncuesta.setCasa(null);
        mEncuesta.setParticipante(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.participante)));

        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantasPersonas)) > 0) mEncuesta.setCuantasPersonas(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantasPersonas)));
        mEncuesta.setCuantasMujeres(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantasMujeres)));
        mEncuesta.setEdadMujer1(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer1)));
        mEncuesta.setEdadMujer2(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer2)));
        mEncuesta.setEdadMujer3(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer3)));
        mEncuesta.setEdadMujer4(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer4)));
        mEncuesta.setEdadMujer5(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer5)));
        mEncuesta.setEdadMujer6(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer7)));
        mEncuesta.setEdadMujer8(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer8)));
        mEncuesta.setEdadMujer9(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer9)));
        mEncuesta.setEdadMujer10(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadMujer10)));
        mEncuesta.setCuantosHombres(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantosHombres)));
        mEncuesta.setEdadHombre1(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre1)));
        mEncuesta.setEdadHombre2(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre2)));
        mEncuesta.setEdadHombre3(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre3)));
        mEncuesta.setEdadHombre4(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre4)));
        mEncuesta.setEdadHombre5(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre5)));
        mEncuesta.setEdadHombre6(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre6)));
        mEncuesta.setEdadHombre7(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre7)));
        mEncuesta.setEdadHombre8(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre8)));
        mEncuesta.setEdadHombre9(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre9)));
        mEncuesta.setEdadHombre10(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.edadHombre10)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCuartos)) > 0) mEncuesta.setCantidadCuartos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCuartos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCuartosDormir)) > 0) mEncuesta.setCantidadCuartosDormir(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCuartosDormir)));
        mEncuesta.setProblemaAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.problemaAgua)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hrsSinServicioAgua)) > 0) mEncuesta.setHrsSinServicioAgua(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hrsSinServicioAgua)));
        mEncuesta.setFrecuenciaSeVaAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.frecuenciaSeVaAgua)));
        mEncuesta.setOtraFrecuenciaSeVaAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otraFrecuenciaSeVaAgua)));
        mEncuesta.setTienePozo(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tienePozo)));
        mEncuesta.setTieneMedidorAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneMedidorAgua)));
        mEncuesta.setTieneTanque(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneTanque)));
        mEncuesta.setUbicacionLlaveAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.ubicacionLlaveAgua)));
        mEncuesta.setLlaveCompartida(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.llaveCompartida)));
        mEncuesta.setAlmacenaAgua(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.almacenaAgua)));
        mEncuesta.setAlmacenaEnBarriles(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.almacenaEnBarriles)));
        mEncuesta.setAlmacenaEnTanques(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.almacenaEnTanques)));
        mEncuesta.setAlmacenaEnPilas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.almacenaEnPilas)));
        mEncuesta.setAlmacenaOtrosRecipientes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.almacenaOtrosRecipientes)));
        mEncuesta.setOtrosRecipientes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otrosRecipientes)));
        mEncuesta.setCepillaPilas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cepillaPilas)));
        mEncuesta.setFrecCepillaPilas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.frecCepillaPilas)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numBarriles)) > 0) mEncuesta.setNumBarriles(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numBarriles)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numTanques)) > 0) mEncuesta.setNumTanques(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numTanques)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numPilas)) > 0) mEncuesta.setNumPilas(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numPilas)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numOtrosRecipientes)) > 0) mEncuesta.setNumOtrosRecipientes(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numOtrosRecipientes)));
        mEncuesta.setBarrilesTapados(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.barrilesTapados)));
        mEncuesta.setTanquesTapados(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tanquesTapados)));
        mEncuesta.setPilasTapadas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.pilasTapadas)));
        mEncuesta.setOtrosRecipientesTapados(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otrosRecipientesTapados)));
        mEncuesta.setCambiadoCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cambiadoCasa)));
        mEncuesta.setRemodeladoCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.remodeladoCasa)));
        mEncuesta.setUbicacionLavandero(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.ubicacionLavandero)));
        mEncuesta.setMaterialParedes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.materialParedes)));
        mEncuesta.setMaterialPiso(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.materialPiso)));
        mEncuesta.setMaterialTecho(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.materialTecho)));
        mEncuesta.setOtroMaterialParedes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroMaterialParedes)));
        mEncuesta.setOtroMaterialPiso(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroMaterialPiso)));
        mEncuesta.setOtroMaterialTecho(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroMaterialTecho)));
        mEncuesta.setCasaPropia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.casaPropia)));
        mEncuesta.setTieneAbanico(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneAbanico)));
        mEncuesta.setTieneTelevisor(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneTelevisor)));
        mEncuesta.setTieneRefrigerador(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneRefrigerador)));
        mEncuesta.setTienAireAcondicionado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tienAireAcondicionado)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numAbanicos)) > 0) mEncuesta.setNumAbanicos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numAbanicos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numTelevisores)) > 0) mEncuesta.setNumTelevisores(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numTelevisores)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numRefrigeradores)) > 0) mEncuesta.setNumRefrigeradores(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numRefrigeradores)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numAireAcondicionado)) > 0) mEncuesta.setNumAireAcondicionado(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numAireAcondicionado)));
        mEncuesta.setAireAcondicionadoFuncionando(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.aireAcondicionadoFuncionando)));
        mEncuesta.setLavadoraFuncionando(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.lavadoraFuncionando)));
        mEncuesta.setTieneMuro(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneMuro)));
        mEncuesta.setTieneInternet(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneInternet)));
        mEncuesta.setTieneInodoro(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneInodoro)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantInodoro)) > 0) mEncuesta.setCantInodoro(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantInodoro)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantLetrina)) > 0) mEncuesta.setCantLetrina(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantLetrina)));
        mEncuesta.setTieneServicioEnergia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneServicioEnergia)));
        mEncuesta.setTieneMedidorEnergia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneMedidorEnergia)));
        mEncuesta.setCasaDosPisos(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.casaDosPisos)));
        mEncuesta.setTieneOtrosServicios(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneOtrosServicios)));
        mEncuesta.setTieneVehiculo(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneVehiculo)));
        mEncuesta.setTieneMoto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneMoto)));
        mEncuesta.setTieneCarro(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCarro)));
        mEncuesta.setTieneMicrobus(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneMicrobus)));
        mEncuesta.setTieneCamioneta(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCamioneta)));
        mEncuesta.setTieneCamion(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCamion)));
        mEncuesta.setTieneOtroMedioTransAuto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneOtroMedioTransAuto)));
        mEncuesta.setOtroMedioTransAuto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroMedioTransAuto)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabMoto)) > 0) mEncuesta.setAnioFabMoto(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabMoto)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCarro)) > 0) mEncuesta.setAnioFabCarro(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCarro)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabMicrobus)) > 0) mEncuesta.setAnioFabMicrobus(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabMicrobus)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCamioneta)) > 0) mEncuesta.setAnioFabCamioneta(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCamioneta)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCamion)) > 0) mEncuesta.setAnioFabCamion(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabCamion)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabOtroMedioTrans)) > 0) mEncuesta.setAnioFabOtroMedioTrans(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioFabOtroMedioTrans)));
        mEncuesta.setMarcaMoto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaMoto)));
        mEncuesta.setMarcaCarro(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaCarro)));
        mEncuesta.setMarcaMicrobus(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaMicrobus)));
        mEncuesta.setMarcaCamioneta(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaCamioneta)));
        mEncuesta.setMarcaCamion(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaCamion)));
        mEncuesta.setMarcaOtroMedioTrans(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.marcaOtroMedioTrans)));
        mEncuesta.setTipoCocina(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tipoCocina)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantosQuemadores)) > 0) mEncuesta.setCuantosQuemadores(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantosQuemadores)));
        mEncuesta.setTieneHorno(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneHorno)));
        mEncuesta.setCocinaConLenia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cocinaConLenia)));
        mEncuesta.setUbicacionCocinaLenia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.ubicacionCocinaLenia)));
        mEncuesta.setPeriodicidadCocinaLenia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.periodicidadCocinaLenia)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numDiarioCocinaLenia)) > 0) mEncuesta.setNumDiarioCocinaLenia(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numDiarioCocinaLenia)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numSemanalCocinaLenia)) > 0) mEncuesta.setNumSemanalCocinaLenia(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numSemanalCocinaLenia)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numQuincenalCocinaLenia)) > 0) mEncuesta.setNumQuincenalCocinaLenia(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numQuincenalCocinaLenia)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numMensualCocinaLenia)) > 0) mEncuesta.setNumMensualCocinaLenia(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.numMensualCocinaLenia)));
        mEncuesta.setTieneAnimales(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneAnimales)));
        mEncuesta.setTieneGallinas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneGallinas)));
        mEncuesta.setTienePatos(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tienePatos)));
        mEncuesta.setTienePerros(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tienePerros)));
        mEncuesta.setTieneGatos(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneGatos)));
        mEncuesta.setTieneCerdos(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCerdos)));
        mEncuesta.setTieneVacas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneVacas)));
        mEncuesta.setTieneCabras(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCabras)));
        mEncuesta.setTieneCaballos(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneCaballos)));
        mEncuesta.setTienePelibueys(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tienePelibueys)));
        mEncuesta.setTieneAves(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneAves)));
        mEncuesta.setTieneOtrosAnimales(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneOtrosAnimales)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadGallinas)) > 0) mEncuesta.setCantidadGallinas(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadGallinas)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPatos)) > 0) mEncuesta.setCantidadPatos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPatos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPerros)) > 0) mEncuesta.setCantidadPerros(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPerros)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadGatos)) > 0) mEncuesta.setCantidadGatos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadGatos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCerdos)) > 0) mEncuesta.setCantidadCerdos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCerdos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadVacas)) > 0) mEncuesta.setCantidadVacas(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadVacas)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCabras)) > 0) mEncuesta.setCantidadCabras(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCabras)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCaballos)) > 0) mEncuesta.setCantidadCaballos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCaballos)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPelibueys)) > 0) mEncuesta.setCantidadPelibueys(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadPelibueys)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadAves)) > 0) mEncuesta.setCantidadAves(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadAves)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadOtrosAnimales)) > 0) mEncuesta.setCantidadOtrosAnimales(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadOtrosAnimales)));
        mEncuesta.setGallinasDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.gallinasDentroCasa)));
        mEncuesta.setPatosDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.patosDentroCasa)));
        mEncuesta.setPerrosDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.perrosDentroCasa)));
        mEncuesta.setGatosDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.gatosDentroCasa)));
        mEncuesta.setCerdosDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cerdosDentroCasa)));
        mEncuesta.setVacasDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.vacasDentroCasa)));
        mEncuesta.setCabrasDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cabrasDentroCasa)));
        mEncuesta.setCaballosDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.caballosDentroCasa)));
        mEncuesta.setPelibueysDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.pelibueysDentroCasa)));
        mEncuesta.setAvesDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.avesDentroCasa)));
        mEncuesta.setOtrosAnimalesDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otrosAnimalesDentroCasa)));
        mEncuesta.setPersonaFumaDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.personaFumaDentroCasa)));
        mEncuesta.setTieneRecoleccionBasura(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneRecoleccionBasura)));
        mEncuesta.setDondePasaRecBasuraOtros(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.dondePasaRecBasuraOtros)));
        mEncuesta.setVistoAnimalesSalvajes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.vistoAnimalesSalvajes)));
        mEncuesta.setVistoAnimalesSalvajesOtros(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.vistoAnimalesSalvajesOtros)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantasVecesRecBasura)) > 0) mEncuesta.setCuantasVecesRecBasura(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantasVecesRecBasura)));
        mEncuesta.setDondePasaRecBasura(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.dondePasaRecBasura)));

        if(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))>0) mEncuesta.setRecordDate(new Date(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))));
        mEncuesta.setRecordUser(cursor.getString(cursor.getColumnIndex(MainDBConstants.recordUser)));
        mEncuesta.setPasive(cursor.getString(cursor.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        mEncuesta.setEstado(cursor.getString(cursor.getColumnIndex(MainDBConstants.estado)).charAt(0));
        mEncuesta.setDeviceid(cursor.getString(cursor.getColumnIndex(MainDBConstants.deviceId)));

        return mEncuesta;
    }
}
