package ni.org.ics.a2cares.app.database.helpers;

import android.content.ContentValues;
import android.database.Cursor;

import java.util.Date;

import ni.org.ics.a2cares.app.database.constants.EncuestasDBConstants;
import ni.org.ics.a2cares.app.database.constants.MainDBConstants;
import ni.org.ics.a2cares.app.domain.survey.EncuestaParticipante;

/**
 * Created by Miguel Salinas on 5/10/2017.
 * V1.0
 */
public class EncuestaParticipanteHelper {

    public static ContentValues crearEncuestaParticipanteContentValues(EncuestaParticipante encuesta){
        ContentValues cv = new ContentValues();

        cv.put(EncuestasDBConstants.codigo, encuesta.getCodigo());
        cv.put(EncuestasDBConstants.participante, encuesta.getParticipante().getCodigo());
        if (encuesta.getFechaEncuesta() != null) cv.put(EncuestasDBConstants.fechaEncuesta, encuesta.getFechaEncuesta().getTime());
        cv.put(EncuestasDBConstants.emancipado, encuesta.getEmancipado());
        cv.put(EncuestasDBConstants.descEmancipado, encuesta.getDescEmancipado());
        cv.put(EncuestasDBConstants.otraDescEmanc, encuesta.getOtraDescEmanc());
        cv.put(EncuestasDBConstants.embarazada, encuesta.getEmbarazada());
        cv.put(EncuestasDBConstants.conoceFUR, encuesta.getConoceFUR());
        if (encuesta.getFur() != null) cv.put(EncuestasDBConstants.fur, encuesta.getFur().getTime());
        cv.put(EncuestasDBConstants.asisteEscuela, encuesta.getAsisteEscuela());
        cv.put(EncuestasDBConstants.gradoEstudia, encuesta.getGradoEstudia());
        cv.put(EncuestasDBConstants.nombreEscuela, encuesta.getNombreEscuela());
        cv.put(EncuestasDBConstants.turno, encuesta.getTurno());
        cv.put(EncuestasDBConstants.cuidan, encuesta.getCuidan());
        cv.put(EncuestasDBConstants.cuantosCuidan, encuesta.getCuantosCuidan());
        cv.put(EncuestasDBConstants.nombreCDI, encuesta.getNombreCDI());
        cv.put(EncuestasDBConstants.direccionCDI, encuesta.getDireccionCDI());
        cv.put(EncuestasDBConstants.otroLugarCuidan, encuesta.getOtroLugarCuidan());
        cv.put(EncuestasDBConstants.alfabeto, encuesta.getAlfabeto());
        cv.put(EncuestasDBConstants.nivelEducacion, encuesta.getNivelEducacion());
        cv.put(EncuestasDBConstants.trabaja, encuesta.getTrabaja());
        cv.put(EncuestasDBConstants.tipoTrabajo, encuesta.getTipoTrabajo());
        cv.put(EncuestasDBConstants.ocupacionActual, encuesta.getOcupacionActual());
        cv.put(EncuestasDBConstants.personaVive, encuesta.getPersonaVive());
        cv.put(EncuestasDBConstants.ordenNac, encuesta.getOrdenNac());
        cv.put(EncuestasDBConstants.padreAlfabeto, encuesta.getPadreAlfabeto());
        cv.put(EncuestasDBConstants.papaNivel, encuesta.getNivelEscolarPadre());
        cv.put(EncuestasDBConstants.trabajaPadre, encuesta.getTrabajaPadre());
        cv.put(EncuestasDBConstants.papaTipoTra, encuesta.getTipoTrabajoPadre());
        cv.put(EncuestasDBConstants.madreAlfabeta, encuesta.getMadreAlfabeta());
        cv.put(EncuestasDBConstants.mamaNivel, encuesta.getNivelEscolarMadre());
        cv.put(EncuestasDBConstants.trabajaMadre, encuesta.getTrabajaMadre());
        cv.put(EncuestasDBConstants.mamaTipoTra, encuesta.getTipoTrabajoMadre());
        cv.put(EncuestasDBConstants.comparteHab, encuesta.getComparteHab());
        cv.put(EncuestasDBConstants.hab1, encuesta.getHab1());
        cv.put(EncuestasDBConstants.hab2, encuesta.getHab2());
        cv.put(EncuestasDBConstants.hab3, encuesta.getHab3());
        cv.put(EncuestasDBConstants.hab4, encuesta.getHab4());
        cv.put(EncuestasDBConstants.hab5, encuesta.getHab5());
        cv.put(EncuestasDBConstants.comparteCama, encuesta.getComparteCama());
        cv.put(EncuestasDBConstants.cama1, encuesta.getCama1());
        cv.put(EncuestasDBConstants.cama2, encuesta.getCama2());
        cv.put(EncuestasDBConstants.cama3, encuesta.getCama3());
        cv.put(EncuestasDBConstants.cama4, encuesta.getCama4());
        cv.put(EncuestasDBConstants.cama5, encuesta.getCama5());
        cv.put(EncuestasDBConstants.fuma, encuesta.getFuma());
        cv.put(EncuestasDBConstants.periodicidadFuma, encuesta.getPeriodicidadFuma());
        cv.put(EncuestasDBConstants.cantidadCigarrillos, encuesta.getCantidadCigarrillos());
        cv.put(EncuestasDBConstants.fumaDentroCasa, encuesta.getFumaDentroCasa());
        cv.put(EncuestasDBConstants.tuberculosisPulmonarActual, encuesta.getTuberculosisPulmonarActual());
        cv.put(EncuestasDBConstants.anioDiagTubpulActual, encuesta.getAnioDiagTubpulActual());
        cv.put(EncuestasDBConstants.mesDiagTubpulActual, encuesta.getMesDiagTubpulActual());
        cv.put(EncuestasDBConstants.tratamientoTubpulActual, encuesta.getTratamientoTubpulActual());
        cv.put(EncuestasDBConstants.completoTratamientoTubpulActual, encuesta.getCompletoTratamientoTubpulActual());
        cv.put(EncuestasDBConstants.tuberculosisPulmonarPasado, encuesta.getTuberculosisPulmonarPasado());
        cv.put(EncuestasDBConstants.fechaDiagTubpulPasadoDes, encuesta.getFechaDiagTubpulPasadoDes());
        cv.put(EncuestasDBConstants.anioDiagTubpulPasado, encuesta.getAnioDiagTubpulPasado());
        cv.put(EncuestasDBConstants.mesDiagTubpulPasado, encuesta.getMesDiagTubpulPasado());
        cv.put(EncuestasDBConstants.tratamientoTubpulPasado, encuesta.getTratamientoTubpulPasado());
        cv.put(EncuestasDBConstants.completoTratamientoTubpulPas, encuesta.getCompletoTratamientoTubpulPas());
        cv.put(EncuestasDBConstants.alergiaRespiratoria, encuesta.getAlergiaRespiratoria());
        cv.put(EncuestasDBConstants.alergiaRespiratoriaAnio, encuesta.getAnioAlergiaRespiratoria());
        cv.put(EncuestasDBConstants.asma, encuesta.getAsma());
        cv.put(EncuestasDBConstants.asmaAnio, encuesta.getAnioAsma());
        cv.put(EncuestasDBConstants.enfermedadCronica, encuesta.getEnfermedadCronica());
        cv.put(EncuestasDBConstants.cardiopatia, encuesta.getCardiopatia());
        cv.put(EncuestasDBConstants.cardiopatiaAnio, encuesta.getAnioCardiopatia());
        cv.put(EncuestasDBConstants.enfermPulmonarObstCronica, encuesta.getEnfermPulmonarObstCronica());
        cv.put(EncuestasDBConstants.enfermPulmonarObstCronicaAnio, encuesta.getAnioEnfermPulmonarObstCronica());
        cv.put(EncuestasDBConstants.diabetes, encuesta.getDiabetes());
        cv.put(EncuestasDBConstants.diabetesAnio, encuesta.getAnioDiabetes());
        cv.put(EncuestasDBConstants.presionAlta, encuesta.getPresionAlta());
        cv.put(EncuestasDBConstants.presionAltaAnio, encuesta.getAnioPresionAlta());
        cv.put(EncuestasDBConstants.otrasEnfermedades, encuesta.getOtrasEnfermedades());
        cv.put(EncuestasDBConstants.descOtrasEnfermedades, encuesta.getDescOtrasEnfermedades());
        cv.put(EncuestasDBConstants.tenidoDengue, encuesta.getTenidoDengue());
        cv.put(EncuestasDBConstants.anioDengue, encuesta.getAnioDengue());
        cv.put(EncuestasDBConstants.diagMedicoDengue, encuesta.getDiagMedicoDengue());
        cv.put(EncuestasDBConstants.dondeDengue, encuesta.getDondeDengue());
        cv.put(EncuestasDBConstants.tenidoZika, encuesta.getTenidoZika());
        cv.put(EncuestasDBConstants.anioZika, encuesta.getAnioZika());
        cv.put(EncuestasDBConstants.diagMedicoZika, encuesta.getDiagMedicoZika());
        cv.put(EncuestasDBConstants.dondeZika, encuesta.getDondeZika());
        cv.put(EncuestasDBConstants.tenidoChik, encuesta.getTenidoChik());
        cv.put(EncuestasDBConstants.anioChik, encuesta.getAnioChik());
        cv.put(EncuestasDBConstants.diagMedicoChik, encuesta.getDiagMedicoChik());
        cv.put(EncuestasDBConstants.dondeChik, encuesta.getDondeChik());
        cv.put(EncuestasDBConstants.vacunaFiebreAma, encuesta.getVacunaFiebreAma());
        cv.put(EncuestasDBConstants.anioVacunaFiebreAma, encuesta.getAnioVacunaFiebreAma());
        cv.put(EncuestasDBConstants.vacunaCovid, encuesta.getVacunaCovid());
        cv.put(EncuestasDBConstants.anioVacunaCovid, encuesta.getAnioVacunaCovid());
        cv.put(EncuestasDBConstants.mesVacunaCovid, encuesta.getMesVacunaCovid());
        cv.put(EncuestasDBConstants.tieneTarjetaVacuna, encuesta.getTieneTarjetaVacuna());
        cv.put(EncuestasDBConstants.fiebre, encuesta.getFiebre());
        cv.put(EncuestasDBConstants.tiempoFiebre, encuesta.getTiempoFiebre());
        cv.put(EncuestasDBConstants.lugarConsFiebre, encuesta.getLugarConsFiebre());
        cv.put(EncuestasDBConstants.noAcudioCs, encuesta.getNoAcudioCs());
        cv.put(EncuestasDBConstants.automedicoFiebre, encuesta.getAutomedicoFiebre());
        cv.put(EncuestasDBConstants.tenidoDengueUA, encuesta.getTenidoDengueUA());
        cv.put(EncuestasDBConstants.unidadSaludDengue, encuesta.getUnidadSaludDengue());
        cv.put(EncuestasDBConstants.centroSaludDengue, encuesta.getCentroSaludDengue());
        cv.put(EncuestasDBConstants.otroCentroSaludDengue, encuesta.getOtroCentroSaludDengue());
        cv.put(EncuestasDBConstants.puestoSaludDengue, encuesta.getPuestoSaludDengue());
        cv.put(EncuestasDBConstants.otroPuestoSaludDengue, encuesta.getOtroPuestoSaludDengue());
        cv.put(EncuestasDBConstants.hospitalDengue, encuesta.getHospitalDengue());
        cv.put(EncuestasDBConstants.otroHospitalDengue, encuesta.getOtroHospitalDengue());
        cv.put(EncuestasDBConstants.hospitalizadoDengue, encuesta.getHospitalizadoDengue());
        cv.put(EncuestasDBConstants.ambulatorioDengue, encuesta.getAmbulatorioDengue());
        cv.put(EncuestasDBConstants.diagnosticoDengue, encuesta.getDiagnosticoDengue());
        cv.put(EncuestasDBConstants.rashUA, encuesta.getRashUA());
        cv.put(EncuestasDBConstants.recuerdaMesRash, encuesta.getRecuerdaMesRash());
        cv.put(EncuestasDBConstants.rashMes, encuesta.getMesRash());
        cv.put(EncuestasDBConstants.rashCara, encuesta.getCaraRash());
        cv.put(EncuestasDBConstants.rashMiembrosSup, encuesta.getMiembrosSupRash());
        cv.put(EncuestasDBConstants.rashTorax, encuesta.getToraxRash());
        cv.put(EncuestasDBConstants.rashAbdomen, encuesta.getAbdomenRash());
        cv.put(EncuestasDBConstants.rashMiembrosInf, encuesta.getMiembrosInfRash());
        cv.put(EncuestasDBConstants.rashDias, encuesta.getDiasRash());
        cv.put(EncuestasDBConstants.consultaRashUA, encuesta.getConsultaRashUA());
        cv.put(EncuestasDBConstants.unidadSaludRash, encuesta.getUnidadSaludRash());
        cv.put(EncuestasDBConstants.centroSaludRash, encuesta.getCentroSaludRash());
        cv.put(EncuestasDBConstants.otroCentroSaludRash, encuesta.getOtroCentroSaludRash());
        cv.put(EncuestasDBConstants.puestoSaludRash, encuesta.getPuestoSaludRash());
        cv.put(EncuestasDBConstants.otroPuestoSaludRash, encuesta.getOtroPuestoSaludRash());
        cv.put(EncuestasDBConstants.diagnosticoRash, encuesta.getDiagnosticoRash());
        cv.put(EncuestasDBConstants.estudiosAct, encuesta.getEstudiosAct());

        if (encuesta.getRecordDate() != null) cv.put(MainDBConstants.recordDate, encuesta.getRecordDate().getTime());
        cv.put(MainDBConstants.recordUser, encuesta.getRecordUser());
        cv.put(MainDBConstants.pasive, String.valueOf(encuesta.getPasive()));
        cv.put(MainDBConstants.estado, String.valueOf(encuesta.getEstado()));
        cv.put(MainDBConstants.deviceId, encuesta.getDeviceid());

        return cv;
    }

    public static EncuestaParticipante crearEncuestaParticipante(Cursor cursor){
        EncuestaParticipante mEncuesta = new EncuestaParticipante();

        mEncuesta.setCodigo(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.codigo)));
        mEncuesta.setParticipante(null);
        if(cursor.getLong(cursor.getColumnIndex(EncuestasDBConstants.fechaEncuesta))>0) mEncuesta.setFechaEncuesta(new Date(cursor.getLong((cursor.getColumnIndex(EncuestasDBConstants.fechaEncuesta)))));
        mEncuesta.setEmancipado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.emancipado)));
        mEncuesta.setDescEmancipado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.descEmancipado)));
        mEncuesta.setOtraDescEmanc(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otraDescEmanc)));
        mEncuesta.setEmbarazada(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.embarazada)));
        mEncuesta.setConoceFUR(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.conoceFUR)));
        if(cursor.getLong(cursor.getColumnIndex(EncuestasDBConstants.fur))>0) mEncuesta.setFur(new Date(cursor.getLong((cursor.getColumnIndex(EncuestasDBConstants.fur)))));
        mEncuesta.setAsisteEscuela(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.asisteEscuela)));
        mEncuesta.setGradoEstudia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.gradoEstudia)));
        mEncuesta.setNombreEscuela(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.nombreEscuela)));
        mEncuesta.setTurno(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.turno)));
        mEncuesta.setCuidan(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cuidan)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantosCuidan)) > 0) mEncuesta.setCuantosCuidan(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cuantosCuidan)));
        mEncuesta.setNombreCDI(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.nombreCDI)));
        mEncuesta.setDireccionCDI(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.direccionCDI)));
        mEncuesta.setOtroLugarCuidan(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroLugarCuidan)));
        mEncuesta.setAlfabeto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.alfabeto)));
        mEncuesta.setNivelEducacion(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.nivelEducacion)));
        mEncuesta.setTrabaja(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.trabaja)));
        mEncuesta.setTipoTrabajo(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tipoTrabajo)));
        mEncuesta.setOcupacionActual(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.ocupacionActual)));
        mEncuesta.setPersonaVive(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.personaVive)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.ordenNac)) > 0) mEncuesta.setOrdenNac(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.ordenNac)));
        mEncuesta.setPadreAlfabeto(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.padreAlfabeto)));
        mEncuesta.setNivelEscolarPadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.papaNivel)));
        mEncuesta.setTrabajaPadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.trabajaPadre)));
        mEncuesta.setTipoTrabajoPadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.papaTipoTra)));
        mEncuesta.setMadreAlfabeta(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.madreAlfabeta)));
        mEncuesta.setNivelEscolarMadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.mamaNivel)));
        mEncuesta.setTrabajaMadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.trabajaMadre)));
        mEncuesta.setTipoTrabajoMadre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.mamaTipoTra)));
        mEncuesta.setComparteHab(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.comparteHab)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab1)) > 0) mEncuesta.setHab1(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab1)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab2)) > 0) mEncuesta.setHab2(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab2)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab3)) > 0) mEncuesta.setHab3(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab3)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab4)) > 0) mEncuesta.setHab4(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab4)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab5)) > 0) mEncuesta.setHab5(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.hab5)));
        mEncuesta.setComparteCama(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.comparteCama)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama1)) > 0) mEncuesta.setCama1(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama1)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama2)) > 0) mEncuesta.setCama2(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama2)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama3)) > 0) mEncuesta.setCama3(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama3)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama4)) > 0) mEncuesta.setCama4(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama4)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama5)) > 0) mEncuesta.setCama5(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cama5)));
        mEncuesta.setFuma(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.fuma)));
        mEncuesta.setPeriodicidadFuma(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.periodicidadFuma)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCigarrillos)) > 0) mEncuesta.setCantidadCigarrillos(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cantidadCigarrillos)));
        mEncuesta.setFumaDentroCasa(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.fumaDentroCasa)));
        mEncuesta.setTuberculosisPulmonarActual(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tuberculosisPulmonarActual)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDiagTubpulActual)) > 0) mEncuesta.setAnioDiagTubpulActual(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDiagTubpulActual)));
        mEncuesta.setMesDiagTubpulActual(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.mesDiagTubpulActual)));
        mEncuesta.setTratamientoTubpulActual(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tratamientoTubpulActual)));
        mEncuesta.setCompletoTratamientoTubpulActual(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.completoTratamientoTubpulActual)));
        mEncuesta.setTuberculosisPulmonarPasado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tuberculosisPulmonarPasado)));
        mEncuesta.setFechaDiagTubpulPasadoDes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.fechaDiagTubpulPasadoDes)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDiagTubpulPasado)) > 0) mEncuesta.setAnioDiagTubpulPasado(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDiagTubpulPasado)));
        mEncuesta.setMesDiagTubpulPasado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.mesDiagTubpulPasado)));
        mEncuesta.setTratamientoTubpulPasado(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tratamientoTubpulPasado)));
        mEncuesta.setCompletoTratamientoTubpulPas(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.completoTratamientoTubpulPas)));
        mEncuesta.setAlergiaRespiratoria(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.alergiaRespiratoria)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.alergiaRespiratoriaAnio)) > 0) mEncuesta.setAnioAlergiaRespiratoria(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.alergiaRespiratoriaAnio)));
        mEncuesta.setAsma(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.asma)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.asmaAnio)) > 0) mEncuesta.setAnioAsma(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.asmaAnio)));
        mEncuesta.setEnfermedadCronica(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.enfermedadCronica)));
        mEncuesta.setCardiopatia(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.cardiopatia)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cardiopatiaAnio)) > 0)  mEncuesta.setAnioCardiopatia(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.cardiopatiaAnio)));
        mEncuesta.setEnfermPulmonarObstCronica(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.enfermPulmonarObstCronica)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.enfermPulmonarObstCronicaAnio)) > 0) mEncuesta.setAnioEnfermPulmonarObstCronica(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.enfermPulmonarObstCronicaAnio)));
        mEncuesta.setDiabetes(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diabetes)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.diabetesAnio)) > 0) mEncuesta.setAnioDiabetes(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.diabetesAnio)));
        mEncuesta.setPresionAlta(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.presionAlta)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.presionAltaAnio)) > 0) mEncuesta.setAnioPresionAlta(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.presionAltaAnio)));
        mEncuesta.setOtrasEnfermedades(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otrasEnfermedades)));
        mEncuesta.setDescOtrasEnfermedades(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.descOtrasEnfermedades)));
        mEncuesta.setTenidoDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tenidoDengue)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDengue)) > 0) mEncuesta.setAnioDengue(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioDengue)));
        mEncuesta.setDiagMedicoDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diagMedicoDengue)));
        mEncuesta.setDondeDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.dondeDengue)));
        mEncuesta.setTenidoZika(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tenidoZika)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioZika)) > 0) mEncuesta.setAnioZika(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioZika)));
        mEncuesta.setDiagMedicoZika(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diagMedicoZika)));
        mEncuesta.setDondeZika(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.dondeZika)));
        mEncuesta.setTenidoChik(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tenidoChik)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioChik)) > 0) mEncuesta.setAnioChik(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioChik)));
        mEncuesta.setDiagMedicoChik(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diagMedicoChik)));
        mEncuesta.setDondeChik(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.dondeChik)));
        mEncuesta.setVacunaFiebreAma(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.vacunaFiebreAma)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioVacunaFiebreAma)) > 0) mEncuesta.setAnioVacunaFiebreAma(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioVacunaFiebreAma)));
        mEncuesta.setVacunaCovid(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.vacunaCovid)));
        if (cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioVacunaCovid)) > 0) mEncuesta.setAnioVacunaCovid(cursor.getInt(cursor.getColumnIndex(EncuestasDBConstants.anioVacunaCovid)));
        mEncuesta.setMesVacunaCovid(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.mesVacunaCovid)));
        mEncuesta.setTieneTarjetaVacuna(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tieneTarjetaVacuna)));
        mEncuesta.setFiebre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.fiebre)));
        mEncuesta.setTiempoFiebre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tiempoFiebre)));
        mEncuesta.setLugarConsFiebre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.lugarConsFiebre)));
        mEncuesta.setNoAcudioCs(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.noAcudioCs)));
        mEncuesta.setAutomedicoFiebre(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.automedicoFiebre)));
        mEncuesta.setTenidoDengueUA(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.tenidoDengueUA)));
        mEncuesta.setUnidadSaludDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.unidadSaludDengue)));
        mEncuesta.setCentroSaludDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.centroSaludDengue)));
        mEncuesta.setOtroCentroSaludDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroCentroSaludDengue)));
        mEncuesta.setPuestoSaludDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.puestoSaludDengue)));
        mEncuesta.setOtroPuestoSaludDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroPuestoSaludDengue)));
        mEncuesta.setHospitalDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.hospitalDengue)));
        mEncuesta.setOtroHospitalDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroHospitalDengue)));
        mEncuesta.setHospitalizadoDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.hospitalizadoDengue)));
        mEncuesta.setAmbulatorioDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.ambulatorioDengue)));
        mEncuesta.setDiagnosticoDengue(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diagnosticoDengue)));
        mEncuesta.setRashUA(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashUA)));
        mEncuesta.setRecuerdaMesRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.recuerdaMesRash)));
        mEncuesta.setMesRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashMes)));
        mEncuesta.setCaraRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashCara)));
        mEncuesta.setMiembrosSupRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashMiembrosSup)));
        mEncuesta.setToraxRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashTorax)));
        mEncuesta.setAbdomenRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashAbdomen)));
        mEncuesta.setMiembrosInfRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashMiembrosInf)));
        mEncuesta.setDiasRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.rashDias)));
        mEncuesta.setConsultaRashUA(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.consultaRashUA)));
        mEncuesta.setUnidadSaludRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.unidadSaludRash)));
        mEncuesta.setCentroSaludRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.centroSaludRash)));
        mEncuesta.setOtroCentroSaludRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroCentroSaludRash)));
        mEncuesta.setPuestoSaludRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.puestoSaludRash)));
        mEncuesta.setOtroPuestoSaludRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.otroPuestoSaludRash)));
        mEncuesta.setDiagnosticoRash(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.diagnosticoRash)));
        mEncuesta.setEstudiosAct(cursor.getString(cursor.getColumnIndex(EncuestasDBConstants.estudiosAct)));

        if(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))>0) mEncuesta.setRecordDate(new Date(cursor.getLong(cursor.getColumnIndex(MainDBConstants.recordDate))));
        mEncuesta.setRecordUser(cursor.getString(cursor.getColumnIndex(MainDBConstants.recordUser)));
        mEncuesta.setPasive(cursor.getString(cursor.getColumnIndex(MainDBConstants.pasive)).charAt(0));
        mEncuesta.setEstado(cursor.getString(cursor.getColumnIndex(MainDBConstants.estado)).charAt(0));
        mEncuesta.setDeviceid(cursor.getString(cursor.getColumnIndex(MainDBConstants.deviceId)));

        return mEncuesta;
    }
}
